// internal/crypto/crypto_test.go
package crypto_test

import (
	"fmt"
	"testing"

	"github.com/mdmclean/kashmere-cli/internal/crypto"
)

func TestDeriveKeyLength(t *testing.T) {
	salt := make([]byte, 32)
	key, err := crypto.DeriveKey("test-passphrase-12chars", salt)
	if err != nil {
		t.Fatal(err)
	}
	if len(key) != 32 {
		t.Errorf("key length: got %d, want 32", len(key))
	}
}

func TestEncryptDecryptRoundTrip(t *testing.T) {
	salt := make([]byte, 32)
	key, _ := crypto.DeriveKey("test-passphrase-12chars", salt)

	plaintext := `{"name":"test"}`
	ciphertext, err := crypto.Encrypt(key, plaintext)
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}

	got, err := crypto.Decrypt(key, ciphertext)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if got != plaintext {
		t.Errorf("got %q, want %q", got, plaintext)
	}
}

func TestSaltBase64RoundTrip(t *testing.T) {
	original := []byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
		17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32}

	encoded := crypto.SaltToBase64(original)
	decoded, err := crypto.SaltFromBase64(encoded)
	if err != nil {
		t.Fatal(err)
	}
	for i, b := range original {
		if decoded[i] != b {
			t.Errorf("byte %d: got %d, want %d", i, decoded[i], b)
		}
	}
}

// TestCompatibilityWithTypeScript verifies the Go implementation can decrypt
// ciphertext produced by the TypeScript shared-crypto library.
//
// The test vector was generated by running in the monorepo:
//
//	cd packages/shared-crypto
//	node -e "
//	  const {deriveKey, encrypt} = require('./dist/index.js');
//	  const salt = new Uint8Array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32]);
//	  deriveKey('test-passphrase-12chars', salt).then(k =>
//	    encrypt('{\"name\":\"test\"}', k).then(c => console.log(c))
//	  );
//	"
func TestCompatibilityWithTypeScript(t *testing.T) {
	const tsVector = "ps+sSXQqeo1Q0iMIa/kY1cRJFcx31FWGXJP8Tz8AANziT5kVsU4xgEAWtw=="

	saltHex := "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
	salt := hexToBytes(t, saltHex)
	key, err := crypto.DeriveKey("test-passphrase-12chars", salt)
	if err != nil {
		t.Fatal(err)
	}

	got, err := crypto.Decrypt(key, tsVector)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if got != `{"name":"test"}` {
		t.Errorf("got %q, want {\"name\":\"test\"}", got)
	}
}

func hexToBytes(t *testing.T, s string) []byte {
	t.Helper()
	b := make([]byte, len(s)/2)
	for i := range b {
		_, err := fmt.Sscanf(s[i*2:i*2+2], "%02x", &b[i])
		if err != nil {
			t.Fatalf("hex decode: %v", err)
		}
	}
	return b
}
